### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by pcminitech** [uw-ictd/colte#46]
│ Failure restarting some services for OpenSSL upgrade                      │
 │                                                                           │
 │ The following services could not be restarted for the OpenSSL library     │
 │ upgrade:                                                                  │
 │                                                                           │
 │ nginx                                                                     │
 │                                                                           │
 │ You will need to start these manually by running '/etc/init.d/<service>   │
 │ start'.                                                                   │
 │

**Comment by pcminitech** [comment]
dpkg: error processing package colte (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for ufw (0.35-5) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.12) ...
Errors were encountered while processing:
 nginx-core
 nginx
 colte-webservices
 colte
E: Sub-process /usr/bin/dpkg returned an error code (1)
W: Operation was interrupted before it could finish

**Comment by kheimerl** [comment]
you have an nginx issue. I saw something similar, I had old nginx links around that were making that package fail to install. See #40

**Comment by pcminitech** [comment]
![issue](https://user-images.githubusercontent.com/35584824/59926565-8e538c00-9408-11e9-9d57-a681dd1a9ff3.PNG)

**Comment by pcminitech** [comment]
It a fresh Ubuntu 18.04 image

**Comment by pcminitech** [comment]
If we comment out this line it works 
include /etc/nginx/sites-enabled/*;
But the web page are not there where do i need to re point this.

**Comment by kheimerl** [comment]
Yeah you need nginx to be operational. The issue doesn't seem to be with colte though:

"Errors were encountered while processing:
nginx-core
nginx"

Those are the base packages and if they didn't install it's got nothing to do with colte.

**Comment by pcminitech** [comment]
Yes If I install Nginx first it works good then run the colte install it breaks. If I revert the snapshot just install colte same thing. I have tried fresh installs of Ubuntu 18.04 same issues ever time.

**Comment by kheimerl** [comment]
huh. the debug you put up there seems to indicate that nginx-core failed to install on its own. They should be sequential. 

Anyhow, if you share some nginx logs I bet we can figure out the issue.

**Comment by spencersevilla** [comment]
Easiest solution is probably to yank the nginx configs out of this package. It’s only used for web forwarding based on host name redirection, since the actual web apps are written in node and run on local host ports 7999 and 8000. I’ve seen nginx make issues like this before, and it shouldn’t break the main install.

**Comment by pcminitech** [comment]
Hi @kheimerl I'm Dalton Gilmore from the baicells facebook page.

**Comment by pcminitech** [comment]
I see what I can do knowing that now.

**Comment by kheimerl** [comment]
Hi Dalton! Hopefully we can help figure this out.

**Comment by spencersevilla** [comment]
@pcminitech Looks like there are two things going on here and I've been able to make a half-fix. First, I removed the nginx dependencies from CoLTE since it actually doesn't need nginx for a minimal install (turns out I had already done this for Debian and just forgot to push the fix for Ubuntu as well). Second, it does look like libssl recently (14 June) broke for Ubuntu 18.04; I saw this bug in your trace and was able to recreate on my machine. That is out of our wheelhouse but it sounds like a fix is coming very soon, there is also a workaround somewhere, you can read more here: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832919

**Comment by spencersevilla** [comment]
@pcminitech we've fixed the nginx issue and it looks like the libssl issue is resolved. On my side, install now works fine for a fresh image of 18.04. Can you confirm this works for you before I close it out? Thanks!!!
