### ISSUE TITLE
Debain 10

### ISSUE THREAD

**Issue by matt9j** [uw-ictd/colte#47]
Hi folks! Debian 10 just landed last weekend-- I wanted to open an issue to track if we want to update the baseline install recommendation from Debian9 to debian10?

**Comment by spencersevilla** [comment]
Great idea. I actually started porting the EPC to Debian three weeks ago (off of a relatively finalized testing version of Buster). Code currently compiles but I have not yet stress-tested it. Will provide running updates here throughout the week!

**Comment by spencersevilla** [comment]
Something worth noting here right off the bat is that I would like to eventually move to Debian 10 and sunset Debian 9 support for one key reason: Our WebAdmin tool requires node-8 (pagination library needs it, I don't know why, doesn't seem too vital) whereas Debian 9 ships with node-4. Rather than force update everyone's node, I've put a comment in the "known issues" section; Debian 10 solves this by shipping with node-10 (I believe).

**Comment by matt9j** [comment]
Okay, great! Keep me posted. I'm trying to integrate CoLTE against the rhizomatica stack this week, so I want to pin a platform down.

**Comment by spencersevilla** [comment]
Wilco.

Aside from this node issue (which is resolved on the EPCs we provided Rhizo) the two stacks should be identical, so sticking to 9 should make your life easiest since I haven’t finished 10 support. If we start diverging more (i.e. you require a newer version of something than is on Debian 9) please let me know and we can talk about how it would relate to the 10 migration.

**Comment by matt9j** [comment]
Hmm, okay. I feel like we may want to just always target the latest node LTS release, regardless of what debain has in their repos. I think node provides official snap packages for supported platforms, of which debian is one. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages

Yeah the rhizo integration will be complicated on anything except debian9 since they run freeswitch bare metal, and it's a monster of a program (IMHO more complicated to build and install than OAI).

**Comment by matt9j** [comment]
Done
